# Generated by Django 3.2.8 on 2021-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30, unique=True)),
                ('message', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'user_message',
            },
        ),
    ]
