# Generated by Django 3.2.8 on 2021-11-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20211101_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='dat',
        ),
    ]
